# Exercises

We will practice calculating and displaying descriptive statistics for one variable. Please complete the following exercises.

## General Social Survey

We will use "descriptive_gss.dta" from Acock (2023). Ingest the data into Stata to complete the exercises.

### Nomimal Variables

Steps
  
  1. Compute a frequency tabulation of marital status
  2. What is the mode of marital status?

### Ordinal Variables

Steps

  1. Compute a frequency tabulation of *strsswkr*.
  2. What is the mode? What does it mean?
  3. Calculate the median. Is it the same as the mode?
  4. Display a histogram of the variable using the *discrete* and *frequency* options.
  5. Display a bar chart of the variable using *(count), over(strsswrk)*

### Quantitative Variables

Steps

  1. Use a tabulation for the discrete variable *educ*
  2. What is the mode for years of education?
  3. Calculate the mean and median of *educ*
  4. Are the median and mean the same as the mode?
  5. Display a bar graph of *educ*
  6. Question: is this a discrete variable or can it be an ordinal variable?

Steps

  1. Calculate the mean and median of *age*
  2. Is the mean and median equal to zero or do they differ?
  2. Is the skewness near zero?
  3. What about the kurtosis? Does it tell us anything about the shape of the distribution?
  4. Display a histogram of *age*
  5. Does the histogram corroborate the results from *sum*?
  6. Display a box plot of *age* by sex.
  7. Do you see any outliers?

## Current Population Survey

We will use the July 2026 Current Population Survey to use descriptive statistics on wages.

Ingestion Steps

  1. Go to the Census Bureau's website and ingest the July 2026 csv file
  2. https://www2.census.gov/programs-surveys/cps/datasets/2026/basic/jul26pub.csv
  3. The data dictionary can be found here: https://www2.census.gov/programs-surveys/cps/datasets/2026/basic/2026_Basic_CPS_Public_Use_Record_Layout_plus_IO_Code_list.txt
  
### Quantitative Variables

Descriptive Statistics Steps

  1. Our variable of interest is *pternwa*.
  2. We use a qualifier *prerelg* as a flag for available earnings (prerelg==1)
  3. Calculate the mean and median of weekly earnings
  4. There appear to be issues. What do you see?
  5. Use the command "gen earnings=pternwa/100"
  6. Recalculate the mean and median.
  
Displaying Steps

  1. Next, we want to display the distribution of the weekly earnings
  2. Use a histogram to display the weekly earnings
  3. Are the data distributed normally?
  4. Do you notice anything unusual about the distrubtion?
  5. Next use a box plot to display the distribution of the data.
  
