# Coding Guide for Folder Structure

Please see Julian Reif's coding guide at https://julianreif.com/guide/. These are very good tips very about repliciability and organization. Having your files organized in a folder as an example below will not only with organization, but with replication, as well. You can hand over the entire folder structure, and another users will be able to run the master do file with just changing the main folder location once.

Folder Structure

  - ├── analysis/
    - ├── data/
    - ├── processed/
    - ├── results/
      - ├── figures/
      - ├── tables/
      - ├── scripts/
        - ├── 1_process_raw_data.do
        - ├── 2_...
    - ├── run.do
  - ├── paper/
    - ├── manuscript.tex
    - ├── figures/
    - ├── tables/

# Executing do-files and making log files

From Mitchell 10.3, you should always use a do file when you work with Stata. I find log files helpful, but do files are essential. Do files provide transparency to show your work, and it help provide replication. One key feature of do files are comments. Comments are an essential part for two reasons. It will help yourself when you go back to your own code to describe what is going one. Second, it helps
with replication, since someone should be able to run your code top to bottom and get the same results that you have in your paper, report, or document.   

*Never* use point and click. It is available in Stata, but don't lower yourself to a SPSS standard.

In case you are new to do files. We'll start off with a simple example. We'll pull some data, summarize some data, and tabulate some data.
```{stata do1, eval=FALSE}
use wws.dta, clear
summarize age wage hours
tabulate married
```
```{stata do2, echo=FALSE}
cd "/Users/Sam/Desktop/Econ 645/Data/Mitchell"
use wws.dta, clear
summarize age wage hours
tabulate married
```
We can look at a similar file called example1.do
```{stata do3, eval=FALSE}
	type example1.do
```
We can actually run a do file within a do file
```{stata, do3.1, eval=FALSE}
do example1.do
```
```{stata do3.2, echo=FALSE}
quietly cd "/Users/Sam/Desktop/Econ 645/Data/Mitchell"
do example1.do
```

You can use the doedit command if you want to open the Do-file Editor, but you can just click to open the Do-File (this is an exception from what I said above).

Since we already have the Do-File Editor open, running the doedit will just open a new blank do file.
```{stata do4, eval=FALSE}
doedit 
```
<b>Note:</b> you can write do files in Notepad or TextEdit, but you don't get any
of the benefits, such as highlighted text.

Let's look at a do file that uses the log command
```{stata do5, eval=FALSE}
type example2.do
```

Let's run it.
```{stata do6, eval=FALSE}
log using example2
use wws2, clear
summarize age wage hours
tabulate married
log close example2
```

*Note:* It is important to note that when opening a log it must end with a "log close" command. If your do files bombs out (fails to finish) before reaching the log close command, your log will remain open.

Even if we close the log file, we'll get an error if we try to run the do file again. So we need to add the replace option.
```{stata do7, eval=FALSE}
log using example2, replace
use wws2, clear
summarize age wage hours
tabulate married
log close
```
```{stata do8, echo=FALSE}
quietly cd "/Users/Sam/Desktop/Econ 645/Data/Mitchell"
log using example2, replace
use wws2, clear
summarize age wage hours
tabulate married
log close
```
