
# Stata Programming Techniques 
A brief overview of techniques that will be helpful for completing assignments and empirical project topics include - Local Macros, Loops, Tempfiles, By Sort and Egen, and Weights<

  1. Macros
  2. Local Macros
  3. Global Macros
  4. Loops
  5. Dataframes and Tempfiles
  6. Appending  
  7. Bysort and EGEN
  8. Survey Weights
  9. Accessing results in Stata's stored memory
  
  
## Stata Programming: Macros

One of the essential parts of Stata programming are macros. Macros variables have many uses and can contain strings or numerics. We can use them in loops, in regressions, in calling temporary files, etc. There are two kinds of macros: local and global.

## Local Macros
Local macros work within a single executed do file and removed once the session is run. If you are running local macros you must run the line of code that initializes the macro and the command that utilizes it.

You need to initialize the local macro
E.g.: local i = 1
*Key*: You need to call the macro with ` key (or left quote key just above tab key) and ' key.
E.g.: display "`i'" 
*E.g.: replace x = 0 if y = `i'
```{stata localmacro1}
local i = 1
display "`i'"
```{stata localmacro2,eval=FALSE}
local k = `i' + 1
display "`k'"
```
```{stata localmacro3,echo=FALSE}
local i = 1
local k = `i' + 1
display "`k'"
```

## Global Macros
Global macros are variables that stays within memory even after a new session is run. These macro varibles can work across multiple do files, as well. You need to initialize a global macro E.g.: 
```{stata global1, eval=FALSE}
global j = 2
```
Next, you call the macro with $

```{stata global2, eval=FALSE}
display "$j"
```
```{stata global3, echo=FALSE}
global j = 2
display "$j"
```
You can use local and global macro variables for qualifiers, as well
```{stata global4, eval=FALSE}
replace z = 1 if y = $i
```

Another great use of macros is to find a list of for local levels of a categorical variable, and store it in macro variable
```{stata macros1, eval=FALSE}
levelsof varname, local(levels) 
foreach l of local levels {
  command if varname == `l'
}
```
We'll demo this later, but it is quite useful

You can also use local macros to test regression models
We'll demo this later, as well

## Looping
*Looping has many uses when you want to apply a function or command over 
*a repeated set of values
*There is forvalues and foreach - I typically use foreach given it's versatility
*but Stata says that forvalues can be more efficient
*E.g.: Loop over years and iterate i

### Loop over a number
```{stata looping1}
local i = 0
foreach num of numlist 2015/2019 {
  display "`num'"
  local i = `i'+1
  display "This is the `i' loop"
}
```

### Loop over a local macro
*E.g.: Loop over months and years to read in new files
```{stata looping2}
local month jan feb mar apr may jun jul aug sep oct nov dec
foreach y of numlist 2018/2019 {
  foreach m of local month {
    local filename = "`m'`y'.dta"
	display "`filename'"
  }
}
```

## Data Frames and Tempfiles

Data frames are a relatively new part of Stata (Stata 16+) that let you switch between datasets. Before you could only work on one dataset at a time. You can read an introduction to Stata data frames from <a href="https://medium.com/the-stata-guide/the-stata-frames-guide-1149b50864e3">
Asjad Naqvi</a>.

For older versions of Stata, we have the tempfiles workaround. Tempfiles are useful since they are a bypass around an older Stata limitation of one dataframe at a time.  Later iterations of Stata introduced the dataframe functionality, but the tempfile method still works well.
We will append three years of CPS MORG data from NBER and generate short 1-year panels. *Note*: Tempfiles are really just macros.

## Appending multiple CPS files 
Get CPS Data



Small CPS Files have only a few variables in them compared to the usual.
The full Census CPS micro data files found at:
<a href="https://www.census.gov/data/datasets/time-series/demo/cps/cps-basic.html">
https://www.census.gov/data/datasets/time-series/demo/cps/cps-basic.html</a>.

Set up initial tempfile so we can add each year of CPS data. Save the macro and set it to emptyok.
```{stata tempfile1, eval=FALSE}
tempfile cps
save `cps', emptyok
```
Create a local variable to loop over each year and month to append monthly CPS files into 1 cps file.
```{stata tempfile2}
cd "/Users/Sam/Desktop/Data/CPS"
*Set month macro
local month jan feb mar apr may jun jul aug sep oct nov dec
local filecount = 0

tempfile cps
save `cps', emptyok

foreach y of numlist 23/24 {

  foreach m of local month {
	    
    *Show the year and month
    display "`m'`y'"
    local filename "small`m'`y'pub.dta"
    display "`filename'"
	    
    *Open the monthly data file
    use "`filename'", clear

	  *Append monthly data file to cps tempfile
	  quietly append using `cps'

	  save `cps', replace
	  clear
	  
	  *Count the number of monthly files appended
	  local filecount = `filecount' + 1
	}
}
*Get the appended CPS File
use `cps'
tab hrmonth hryear4
save "cps23_24.dta", replace
```

CPS Basic Data Dictionary can be found at:
<a href="https://www2.census.gov/programs-surveys/cps/datasets/2022/basic/2020_Basic_CPS_Public_Use_Record_Layout_plus_IO_Code_list.txt">
CPS Basic Data Dictionary</a>.</p> 

Check all years are there

## By Sort and EGEN
Please note that we will get into bysort egen later in the semester. However, bysort: egen is a powerful combination that it is worth bring up now. You can summarize, replace, or create new variables by multiple groups 
with the by sort and egen commands
Let's generate laborforce

  1. 1 is employed at work; 
  2. 2 is employed absent; 
  3. 3 is unemployed layoff; 
  4. 4 is unemployed looking;
  5. 5 is NILF retired; 
  6. 6 is NILF disabiled; and 
  7. 7 is NILF other
```{stata sort1, eval=FALSE}
gen laborforce = .
replace laborforce = 0 if pemlr >= 5 & pemlr <= 7
replace laborforce = 1 if pemlr >= 1 & pemlr <= 4
label define laborforce1 0 "NILF" 1 "Labor Force"
label values laborforce laborforce1
tab laborforce

gen employed = .
replace employed = 0 if pemlr >= 3 & pemlr <= 7
replace employed = 1 if pemlr >= 1 & pemlr <= 2
label define employed1 0 "Not Employed" 1 "Employed"
label values employed employed1
tab employed
```

Generate a race/ethnicity category from existing 
```{stata sort2, eval=FALSE}
gen race_ethnicity = .
replace race_ethnicity = 1 if ptdtrace == 1 & pehspnon == 2
replace race_ethnicity = 2 if ptdtrace == 2 & pehspnon == 2	
replace race_ethnicity = 3 if pehspnon == 1
replace race_ethnicity = 4 if ptdtrace == 3 & pehspnon == 2
replace race_ethnicity = 5 if (ptdtrace == 4 | ptdtrace == 5) & pehspnon == 2
replace race_ethnicity = 6 if (ptdtrace >= 6 & ptdtrace <= 26) & pehspnon == 2
label define race_ethnicity1 1 "White NH" 2 "Black NH" 3 "Hispanic or Latino/a" ///
4 "Native American NH" 5 "Asian or Pacific Islander NH" 6 "Multiracial NH"
label values race_ethnicity race_ethnicity1
tab race_ethnicity 
```

Sort by Sex
```{stata sort3, eval=FALSE}
sort pesex
*Summarize laborforce by sex
by pesex: sum laborforce
bysort: sum laborforce
```

Sort by Sex and Race.
```{stata sort4, eval=FALSE}
sort pesex race_ethnicity
*Summarize laborforce by sex and race
by pesex race_ethnicity: sum laborforce
bysort pesex race_ethnicity: sum laborforce
```
Generate Age Bin to find individuals over 16.
```{stata sort5, eval=FALSE}
gen over_16 = .
replace over_16 = 0 if prtage < 16
replace over_16 = 1 if prtage >= 16
label define over_16a 0 "Under 16" 1 "16 and older"
label values over_16 over_16a
tab over_16
```
Generate unweighted laborforce participation rate for each group with by sort and egen. Bysort works, as well, but I usually use sort on one line and by on the other
```{stata sort6, eval=FALSE}
sort pesex race_ethnicity
by pesex race_ethnicity: egen mean_lfpr = mean(laborforce) if over_16 == 1
by pesex race_ethnicity: sum mean_lfpr
```

```{stata sort7, eval=FALSE}
*Counting and indexing/subscripting within groups
gen idcount = .
by pesex race_ethnicity: replace idcount = _n
gen idcount2 = .
by pesex race_ethnicity: replace idcount2 = idcount[_N]
```

## Retrieving estimates stored in Stata's memory

Instead manually entering summary or regression results, we can use scalars in Stata's memory to retrieve the information. This reduces human error of copying and pasting. 

For summary statistics we can use the **return list** command.

```{stata mem1}
cd "/Users/Sam/Desktop/Data/CPS"
use smalljan24pub.dta, clear
sum pternwa if prerelg==1

return list

gen demean_earnings=pternwa-`r(mean)' if prerelg==1
summarize demean_earnings
```
We can also grab information about a regression
```{stata mem2}
cd "/Users/Sam/Desktop/Data/CPS"
use smalljan24pub.dta, clear
gen lnearn=ln(pternwa) if prerelg==1
gen exp=prtage-16
replace exp=0 if exp==-1

reg lnearn c.exp##c.exp i.peeduca i.peernlab if prerelg==1

ereturn list

matrix list e(b)

*Coefficients and standard errors
display _b[1.peernlab] _se[1.peernlab]
```
## Survey Weights

We can use the Current Population Survey public use microdata and replicate published BLS numbers. We need to adjust our numbers with the appropriate weights in order to replicate the published numbers.

First, we need to adjust weights the weights. In the CSV files the weights need to be divided by 1000 since the documentation says implies 4 decimals.

Composite weights *cmpwgt2*</b>* are used for final BLS tabulations of labor force
```{stata wts1, eval=FALSE}

gen cmpwgt2 = pwcmpwgt/10000
```

Outgoing Rotation Weights *pworwgt* are used for earnings only person in interviews 4 and 8
```{stata wts2, eval=FALSE}
gen orwgt2 = pworwgt/10000
```

PWSSWGT weights are used for general tabulations of sex, race, states, etc.
```{stata wts3, eval=FALSE}
gen sswgt2 = pwsswgt/10000
```
*PWVETWGT* are used to study the veteran population 
```{stata wts4, eval=FALSE}
gen vetwgt2 = pwvetwgt/10000
```
*PWLWGT* are weights used to study someone over multiple CPS interviews
```{stata wts5, eval=FALSE}
gen lgwgt2 = pwlgwgt/10000
```

If we are appending all months, we need to divide by 12 for the Basic CPS to get annual weights.
```{stata wts6, eval=FALSE}
	replace cmpwgt2 = cmpwgt2/12
```
If we are appending all months across multiple years, we need to get a composite weight for all of the CPS files
```{stata wts7, eval=FALSE}
cd "/Users/Sam/Desktop/Data/CPS"
use cps23_24.dta
gen cmpwgt3 = pwcmpwgt/24
```

Use the SvySet command to set up the survey design. 
```{stata wts8, eval=FALSE}
	svyset [pw=cmpwgt3]
```

Use the svy: command vars to utilize the survey design.
```{stata wts9, eval=FALSE}
	svy: tab employed hryear4, count cellwidth(20) format(%20.2gc)
```
```{stata wts10}
cd "/Users/Sam/Desktop/Data/CPS"
use cps23_24.dta
gen cmpwgt3 = pwcmpwgt/10000
replace cmpwgt3 = cmpwgt3/12
svyset [pw=cmpwgt3]
gen employed = .
replace employed = 0 if pemlr >= 3 & pemlr <= 7
replace employed = 1 if pemlr >= 1 & pemlr <= 2
label define employed1 0 "Not Employed" 1 "Employed"
label values employed employed1
tab employed
svy: tab employed hryear4, count cellwidth(20) format(%20.2gc)
```
