# Solutions

Here are the solutions to the exercises 

## Importing dta files

Steps:

  1. Go to NBER Current Population Survey (CPS) Merged Outgoing Rotation Group: https://data.nber.org/morg/annual/
  2. Download and ingest the 2024 data
  3. Use the *use* command to ingest the CPS data
  4. Use the *list* command to find the State and County of the 200th observation.
  5. What is the County and State of the 200th observation
  6. Hint: Search for County FIPS code (e.g.: https://fipsdecoder.com/county-fips-codes)

```{stata useex1}
use https://data.nber.org/morg/annual/morg24.dta, clear
list stfips county in 200
```

The 200th observation lives in Mobile County, Alabama.

## Importing csv files

Steps:

  1. Go to the Census Bureau's Current Population Survey home page
  2. Download the July 2026 csv file
  3. Use the *import delimited* command to ingest the July 2026 CPS file
  4. What is the sex (pesex) and labor force status (pemlr) of the 50th observation?
  5. Use the CPS data dictioary: https://www2.census.gov/programs-surveys/cps/datasets/2026/basic/2026_Basic_CPS_Public_Use_Record_Layout_plus_IO_Code_list.txt

```{stata csvex1}
import delimited using "https://www2.census.gov/programs-surveys/cps/datasets/2026/basic/jul26pub.csv", clear
list pesex pemlr in 50
```

The 50th observation is male, who is unemployed - looking for employment 

## Importing Excel files

Steps:

  1. Go to St. Louis Federal Reserve Board FRED site for the unemployment rate: https://fred.stlouisfed.org/series/UNRATE/
  2. Download the excel file "UNRATE.xlsx"
  3. Import the excel file with the *import excel* command.
  4. List the unemployment and date variables
  5. What is the unemployment rate for May 2023?
  
```{stata excelex1}
import excel using "/Users/Sam/Desktop/Econ 643/Data/UNRATE.xlsx", sheet("Monthly") clear
list in 906
```

The unemployment rate in May 2023 was 3.6%

## Importing SAS files

Steps:

  1. Download the NBER MEPS Panel 24 Longitudinal Data File https://data.nber.org/meps/h225/h225.sas7bdat
  2. Import the Sas file into Stata
  3. List the Person ID (DUPERSID, Year of Birth (DOBYY), and Death Status during 2019-2020 (DIED) for the first 10 observations
  4. Codebook: https://meps.ahrq.gov/mepsweb/data_stats/download_data/pufs/h225/h225cb.pdf
  5. Did any one of the first 10 observations die during 2019-2020 panel?
  
```{stata sasex1}
import sas using "/Users/Sam/Desktop/Econ 643/Data/h225.sas7bdat", clear
list DUPERSID DOBYY DIED in 1/10
```

None of the first 10 observations died during 2019-2020 panel.

## Import an SPSS file

Steps:

  1. Download the following file from Stata: https://www.stata.com/sampledata/auto.sav
  2. Use the import command to ingest an SPSS file
  3. List the first 10 observations' make, price, and miles per gallon
  4. What is the Miles per Gallon for the second observation?
  
```{stata spssex1}
import spss using "https://www.stata.com/sampledata/auto.sav"
list make price mpg in 1/10
list mpg in 2
```

The second observation has receives 17 miles per gallon.
