# Labeling Data

Mitchell's 5th chapter has a bunch of useful information, but the most 
important parts are *label define* (and its two options of *add* and *modify*), *label values*, and time formatting. 

## Describing datasets

We have seen the *describe* command before, but it is a very useful command to being working with data. It provides the varible name, storage type, display format, value label, and variable label, Let's get some data on the survey of graduate students. 

```{stata des1}
cd "/Users/Sam/Desktop/Econ 645/Data/Mitchell"
use "survey7.dta", clear
describe
```

We also have a short option, but it just contain general information.
```{stata des2, eval=FALSE}
describe, short
```

```{stata des2_1, echo=FALSE}
quietly{
cd "/Users/Sam/Desktop/Econ 645/Data/Mitchell"
use "survey7.dta", clear
}
describe, short
```

We can subset the variables we want to describe if we want
```{stata des3, eval=FALSE}
describe id gender race
```

```{stata des3_1, echo=FALSE}
quietly {
cd "/Users/Sam/Desktop/Econ 645/Data/Mitchell"
use "survey7.dta", clear
}
describe id gender race
```

Finally, the command *codebook* provides a deep dive into your dataset. This is very useful for looking at the value labels. We only see the value label name in the *describe* command, but the *codebook* command provides more information, such as type of variable, label name, range of values, unique values, missing, value labels, missing value labels (if any).
```{stata des4, eval=FALSE}
codebook
```

```{stata des4_1, echo=FALSE}
quietly {
cd "/Users/Sam/Desktop/Econ 645/Data/Mitchell"
use "survey7.dta", clear
}
codebook
```

We can go by variables.
```{stata des5, eval=FALSE}
codebook race
```

```{stata des5_1, echo=FALSE}
quietly {
cd "/Users/Sam/Desktop/Econ 645/Data/Mitchell"
use "survey7.dta", clear
}
codebook race
```

We can go by variables and notes
```{stata des6, eval=FALSE}
codebook havechild, notes
```

```{stata des6_1, echo=FALSE}
quietly {
cd "/Users/Sam/Desktop/Econ 645/Data/Mitchell"
use "survey7.dta", clear
}
codebook havechild, notes
```

We can look at the variable and missing value labels with the option *mv*. I recommend that you don't label the missing values unless it is absolutely necessary. Different types of missing values besides "." cause problems down the road, especially with the *marginsplot* command.

```{stata des7, eval=FALSE}
codebook ksex, mv
```

```{stata des7_1, echo=FALSE}
quietly {
cd "/Users/Sam/Desktop/Econ 645/Data/Mitchell"
use "survey7.dta", clear
}
codebook ksex, mv
```
If you are interested in the different languages labels it is on page 112. 

The *lookfor* command will return all variables with the search word. This is a bit redundent, since this is available in the variable window. But, it provides more space to look.
```{stata des8, eval=FALSE}
lookfor birth
```

```{stata des8_1, echo=FALSE}
quietly {
cd "/Users/Sam/Desktop/Econ 645/Data/Mitchell"
use "survey7.dta", clear
}
lookfor birth
```

We can also search for the notes by the search word
```{stata des8_5, eval=FALSE}
notes search birth
```

```{stata des8_51, echo=FALSE}
quietly {
cd "/Users/Sam/Desktop/Econ 645/Data/Mitchell"
use "survey7.dta", clear
}
notes search birth
```

We can see the formats of the variables as well
```{stata des9, eval=FALSE}
list income bday
describe income bday
```

```{stata des9_1, echo=FALSE}
quietly {
cd "/Users/Sam/Desktop/Econ 645/Data/Mitchell"
use "survey7.dta", clear
}
list income bday
describe income bday
```

We can see that the format for income is %11.1fc and the format for bday is %td

## Labeling variables
Labeling the variables is a very helpful shortcut to describe what the variable contain without having to go back to the data dicionary. Sometimes we want a short and concise label if we are exporting labels to regression tables, or sometimes we want longer variable labels to give us context of the variable.

Let's get some data on graduate students and use the *describe* command.
```{stata lab1}
cd "/Users/Sam/Desktop/Econ 645/Data/Mitchell"
use "survey1.dta", clear
describe 
```

We have no variable labels, so we will need to provide some so future users have an understand what the data are. We will use the *label variable* command to describe the variable.
```{stata lab2, eval=FALSE}
label variable id "Identification variable"
label variable gender "Gender of the student"
label variable race "Race of the student"
label variable havechild "Given birth to a child"
label variable ksex "Sex of child"
label variable bday "Birthday of student"
label variable income "Income of student"
label variable kbdays "Birthday of child"
label variable kidname "Name of child"
describe
```

```{stata lab2_1, echo=FALSE}
quietly {
cd "/Users/Sam/Desktop/Econ 645/Data/Mitchell"
use "survey1.dta", clear
}
label variable id "Identification variable"
label variable gender "Gender of the student"
label variable race "Race of the student"
label variable havechild "Given birth to a child"
label variable ksex "Sex of child"
label variable bday "Birthday of student"
label variable income "Income of student"
label variable kbdays "Birthday of child"
label variable kidname "Name of child"
describe
```

We can simply change the variable label with running the command again with the new variable label.
```{stata lab3, eval=FALSE}
label variable id "Unique identification variable"
describe
save survey2, replace
```

```{stata lab3_1, echo=FALSE}
quietly {
cd "/Users/Sam/Desktop/Econ 645/Data/Mitchell"
use "survey1.dta", clear
label variable id "Identification variable"
label variable gender "Gender of the student"
label variable race "Race of the student"
label variable havechild "Given birth to a child"
label variable ksex "Sex of child"
label variable bday "Birthday of student"
label variable income "Income of student"
label variable kbdays "Birthday of child"
label variable kidname "Name of child"
}
label variable id "Unique identification variable"
describe
save survey2, replace
```

## Labeling values
Labeling values is a very practice way of analyzing data without having to go back to the data dictionary. Labeling values requires two commands: 

  1. *label define* to define a label that can be used across many different variables.
  2. *label variable* to place a label onto a variable.

Labeling values is a bit different than labeling variables, since we need to modify or replace after a label has been defined. If you try to change a label, then you will get an error unless you use *add*, *modify* or *replace*

Let's look at our codebook
```{stata lab4}
cd "/Users/Sam/Desktop/Econ 645/Data/Mitchell"
use survey2, clear
codebook 
```

We have our variable labels from 5.3, but now we need to label the values so replicators can know what the data are without having to reference the data dictionary for every variable. We will use the *label define* command to create a new label.

First we need to define a label with label define
```{stata lab5, eval=FALSE}
label define racelabel 1 "White" 2 "Asian" 3 "Hispanic" 4 "Black"
```

Next we need to label the values of the variable with *label values* command and we'll look at the codebook again.
```{stata lab6, eval=FALSE}
label values race racelabel
codebook race
```

```{stata lab6_1, echo=FALSE}
quietly {
cd "/Users/Sam/Desktop/Econ 645/Data/Mitchell"
use survey2, clear
label define racelabel 1 "White" 2 "Asian" 3 "Hispanic" 4 "Black"
}
label values race racelabel
codebook race
```

We are still missing a value label for 5, which is Other, so we need to modify our defined label race1. If we do not modify our label, we will get an error if we try to label values again.  We can use the *add* option in label define.
```{stata lab7, eval=FALSE}
label define racelabel 5 "Other", add
```

If we want to modify an existing label, we can use the *modify* option in label define.
```{stata lab8, eval=FALSE}
label define racelabel 4 "African American", modify
codebook race
```

```{stata lab8_1, echo=FALSE}
quietly {
cd "/Users/Sam/Desktop/Econ 645/Data/Mitchell"
use survey2, clear
label define racelabel 1 "White" 2 "Asian" 3 "Hispanic" 4 "Black"
label define racelabel 5 "Other", add
label values race racelabel
}
label define racelabel 4 "African American", modify
codebook race
```

Labeling missing is something that I don't recommend, but we'll show an example here.
```{stata lab9, eval=FALSE}
label define mfkid 1 "Male" 2 "Female" .u "Unknown" .n "NA"
label values ksex mfkid
codebook ksex

label define havechildlabel 0 "Don't have a child" 1 "Have a child" .u "Unknown" .n "NA"
label values havechild havechildlabel
codebook havechild
```

```{stata lab9_1, echo=FALSE}
quietly {
cd "/Users/Sam/Desktop/Econ 645/Data/Mitchell"
use survey2, clear
label define racelabel 1 "White" 2 "Asian" 3 "Hispanic" 4 "Black"
label define racelabel 5 "Other", add
label define racelabel 4 "African American", modify
}
label define mfkid 1 "Male" 2 "Female" .u "Unknown" .n "NA"
label values ksex mfkid
codebook ksex

label define havechildlabel 0 "Don't have a child" 1 "Have a child" .u "Unknown" .n "NA"
label values havechild havechildlabel
codebook havechild
```
We can look at our label list to see what we have define so far. We can use the *label list* command to see our labels.
```{stata lab10, eval=FALSE}
label list
```

```{stata lab10_1, echo=FALSE}
quietly {
cd "/Users/Sam/Desktop/Econ 645/Data/Mitchell"
use survey2, clear
label define racelabel 1 "White" 2 "Asian" 3 "Hispanic" 4 "Black"
label define racelabel 5 "Other", add
label define racelabel 4 "African American", modify
label define mfkid 1 "Male" 2 "Female" .u "Unknown" .n "NA"
label values ksex mfkid
label define havechildlabel 0 "Don't have a child" 1 "Have a child" .u "Unknown" .n "NA"
label values havechild havechildlabel
}
label list
```

The *numlabel* command is an interesting command. It takes the guess work out of knowing the numeric value of the category by appending the numeric value with the label value.
```{stata lab11, eval=FALSE}
numlabel racelabel, add
label list racelabel
tabulate race
```

```{stata lab11_1, echo=FALSE}
quietly {
cd "/Users/Sam/Desktop/Econ 645/Data/Mitchell"
use survey2, clear
label define racelabel 1 "White" 2 "Asian" 3 "Hispanic" 4 "Black"
label define racelabel 5 "Other", add
label define racelabel 4 "African American", modify
label define mfkid 1 "Male" 2 "Female" .u "Unknown" .n "NA"
label values ksex mfkid
label define havechildlabel 0 "Don't have a child" 1 "Have a child" .u "Unknown" .n "NA"
label values havechild havechildlabel
}
numlabel racelabel, add
label list racelabel
tabulate race
```

And, if we don't like it or don't need it any more, we can remove the numeric values with the *remove* option.
```{stata lab12, eval=FALSE}
numlabel racelabel, remove
tabulate race
```

```{stata lab12_1, echo=FALSE}
quietly {
cd "/Users/Sam/Desktop/Econ 645/Data/Mitchell"
use survey2, clear
label define racelabel 1 "White" 2 "Asian" 3 "Hispanic" 4 "Black"
label define racelabel 5 "Other", add
label define racelabel 4 "African American", modify
label define mfkid 1 "Male" 2 "Female" .u "Unknown" .n "NA"
label values ksex mfkid
label define havechildlabel 0 "Don't have a child" 1 "Have a child" .u "Unknown" .n "NA"
label values havechild havechildlabel
numlabel racelabel, add
}
numlabel racelabel, remove
tabulate race
```

We can add additional characters with *numlabel* as well, such as "#=" or "#) " with the *mask* option
```{stata lab13, eval=FALSE}
numlabel racelabel, add mask("#) ")
tabulate race
```

```{stata lab13_1, echo=FALSE}
quietly {
cd "/Users/Sam/Desktop/Econ 645/Data/Mitchell"
use survey2, clear
label define racelabel 1 "White" 2 "Asian" 3 "Hispanic" 4 "Black"
label define racelabel 5 "Other", add
label define racelabel 4 "African American", modify
label define mfkid 1 "Male" 2 "Female" .u "Unknown" .n "NA"
label values ksex mfkid
label define havechildlabel 0 "Don't have a child" 1 "Have a child" .u "Unknown" .n "NA"
label values havechild havechildlabel
}
numlabel racelabel, add mask("#) ")
tabulate race
```

We can remove the mask with *remove* plus the *mask* option
```{stata lab14, eval=FALSE}
numlabel racelabel, remove mask("#) ")
tabulate race
```

```{stata lab14_1, echo=FALSE}
quietly {
cd "/Users/Sam/Desktop/Econ 645/Data/Mitchell"
use survey2, clear
label define racelabel 1 "White" 2 "Asian" 3 "Hispanic" 4 "Black"
label define racelabel 5 "Other", add
label define racelabel 4 "African American", modify
label define mfkid 1 "Male" 2 "Female" .u "Unknown" .n "NA"
label values ksex mfkid
label define havechildlabel 0 "Don't have a child" 1 "Have a child" .u "Unknown" .n "NA"
label values havechild havechildlabel
numlabel racelabel, add
numlabel racelabel, remove
numlabel racelabel, add mask("#) ")
}
numlabel racelabel, remove mask("#) ")
tabulate race
```

```{stata lab14_2, eval=FALSE}
save survey3, replace
```

## Labeling utilities
Stata has label utilities to manage the labels defined. The first one is *label dir* to see the labels names available in a quick and more concise way than using the codebook command.

For me, I think that *label list* will be your most useful command here.

Quick check of your label directory
```{stata lab15}
cd "/Users/Sam/Desktop/Econ 645/Data/Mitchell"
use survey3, clear
label dir
```

The *label list* command gives a more comprehensive view of your labels that includes the value labels associated with the value label name

```{stata lab16, eval=FALSE}
label list
```

```{stata lab16_1, echo=FALSE}
quietly {
cd "/Users/Sam/Desktop/Econ 645/Data/Mitchell"
use survey3, clear
}
label list
```

The *label save* command will save your labels into a do file for future use. Our do file name is stated after the using statement.
```{stata lab17, eval=FALSE}
label save havechildlabel racelabel using surveylabs, replace
type surveylabs.do
```

```{stata lab17_1, echo=FALSE}
quietly {
cd "/Users/Sam/Desktop/Econ 645/Data/Mitchell"
}
type surveylabs.do
```

The *labelbook* command provides information similar to *codebook* but only for the labels that are defined.
```{stata lab18, eval=FALSE}
labelbook
labelbook racelabel
```

```{stata lab18_1, echo=FALSE}
quietly {
cd "/Users/Sam/Desktop/Econ 645/Data/Mitchell"
use survey3, clear
}
labelbook
labelbook racelabel
```

The *problem* option for *labelbook* provides information to alert the users of any problems
```{stata lab19, eval=FALSE}
labelbook, problem
```

```{stata lab19_1, echo=FALSE}
quietly {
cd "/Users/Sam/Desktop/Econ 645/Data/Mitchell"
use survey3, clear
}
labelbook, problem
```


We can have a more detailed look with the *detail* and *problem* options
```{stata lab20, eval=FALSE}
labelbook racelabel, problem detail
```

```{stata lab20_1, echo=FALSE}
quietly {
cd "/Users/Sam/Desktop/Econ 645/Data/Mitchell"
use survey3, clear
}
labelbook racelabel, problem detail
```

## Labeling variables and values in different languages

We will not be covering this, but if you are interested, please review pages 127-132.

## Using Notes
The *note* commmand can be helpful for future users or for replicators.  If you use the *note* command without specifying the variable, then it is a general note that will show up under the _dta note. If you add a variable in front of the *note* command, like note var1:, then you will add a note to the variable

Let's add some general notes.
```{stata note1, eval=FALSE}
note: This was based on the dataset called survey1.txt
```

```{stata note1_1, echo=FALSE}
quietly {
cd "/Users/Sam/Desktop/Econ 645/Data/Mitchell"
use survey3, clear
}
note: This was based on the dataset called survey1.txt
```

Adding *TS* to the end adds a timestamp, which is a nice feature.
```{stata note2, eval=FALSE}
note: The missing values for havechild and childage were coded using -1 and -2 but were converted to .n and .u TS
```	  

Let's call our notes with the *notes* command.
```{stata note3, eval=FALSE}
notes
```

```{stata note3_1, echo=FALSE}
quietly {
cd "/Users/Sam/Desktop/Econ 645/Data/Mitchell"
use survey3, clear
note: This was based on the dataset called survey1.txt
note: The missing values for havechild and childage were coded using -1 and -2 but were converted to .n and .u TS
}
notes
```

Let's add some notes to our variables
```{stata note4, eval=FALSE}
note race: The other category includes people who specified multiple races
note race: This is another note
note race: This is a third note
```

We can just call a particular variable for notes
```{stata note5, eval=FALSE}
notes race
```

We can just call a particular variable for notes
```{stata note5_1, echo=FALSE}
quietly {
cd "/Users/Sam/Desktop/Econ 645/Data/Mitchell"
use survey3, clear
note: This was based on the dataset called survey1.txt
note: The missing values for havechild and childage were coded using -1 and -2 but were converted to .n and .u TS
note race: The other category includes people who specified multiple races
note race: This is another note
note race: This is a third note
}
notes race
```

Let say we added an unhelpful note, then we can drop it with the *notes drop* command and we want to drop the second note.

```{stata note6, eval=FALSE}
notes drop race in 2
notes race
```

```{stata note6_1, echo=FALSE}
quietly {
cd "/Users/Sam/Desktop/Econ 645/Data/Mitchell"
use survey3, clear
note: This was based on the dataset called survey1.txt
note: The missing values for havechild and childage were coded using -1 and -2 but were converted to .n and .u TS
note race: The other category includes people who specified multiple races
note race: This is another note
note race: This is a third note
}
notes drop race in 2
notes race
```

Notice that we have a gap in the sequence of numbering. We can fix that with the *notes renumber* command.
```{stata note7, eval=FALSE}
notes renumber race
notes race
```

```{stata note7_1, echo=FALSE}
quietly {
cd "/Users/Sam/Desktop/Econ 645/Data/Mitchell"
use survey3, clear
note: This was based on the dataset called survey1.txt
note: The missing values for havechild and childage were coded using -1 and -2 but were converted to .n and .u TS
note race: The other category includes people who specified multiple races
note race: This is another note
note race: This is a third note
notes drop race in 2
}
notes renumber race
notes race
```

We can also search notes with the notes search "string" command.
```{stata note8, eval=FALSE}
notes search .u
```

```{stata note8_1, echo=FALSE}
quietly {
cd "/Users/Sam/Desktop/Econ 645/Data/Mitchell"
use survey3, clear
note: This was based on the dataset called survey1.txt
note: The missing values for havechild and childage were coded using -1 and -2 but were converted to .n and .u TS
note race: The other category includes people who specified multiple races
note race: This is another note
note race: This is a third note
notes drop race in 2
notes renumber race
}
notes search .u
```

## Formatting the display of variables
Formatting data will be more common than you expect. It can be a pain when dealing with numbers in the millions or billions and you lack commas. We can format our data with the *format* command.

### Format numerics

Let's get our survey data and list the first 5 observations for id and income


Let's look at the format of income.
```{stata for1}
cd "/Users/Sam/Desktop/Econ 645/Data/Mitchell"
use survey5, clear
describe income
list id income in 1/5
```

The format is *%9.0g*. We always have *%* in front of our format and *g* is a general way of displaying incomes using a width of nine digits and decides for us the best way to display the values. *g* means general here.

*%<w>.0g* means general - find the best way to show the decimals.

Note: *%<w>.<d>g* will change the format to exponent if necessary. Also *<d>* is usually set to 0 with *g*.

*%<w>.<d>f* means fixed - *w* is the width, *d* is the decimals, and *f* means fixed

*%<w>.<d>fc* means fixed with commas - *w* is the width, *d* is the decimals, *f* means fixed, and *c* means comma

*%<w>.0gc* means general with commas - *w* is the width, setting 0 means Stata will decide the decimals, *g* means general, and *c* means comma

The manual is helpful for formatting: https://www.stata.com/manuals/dformat.pdf

Example 1: *format* v1 *%10.0g* - Width of 10 digits and decimals will be decided.

Example 2: *format* v2 *%4.1f* - Show 3 digits in v3 and 1 decimal

Example 3: *format* v3 *%6.1fc* - Show 4 digits plus the comma plus 1 digit

Let's get more control over the income format and use the *%w.df* format. We want a total of 12 digits with 2 decimals places, which means we have 10 digits on the left side of the "."
```{stata for2, eval=FALSE}
format income %12.2f
list income in 1/5
```

```{stata for2_1, echo=FALSE}
quietly {
cd "/Users/Sam/Desktop/Econ 645/Data/Mitchell"
use survey5, clear
}
format income %12.2f
list income in 1/5
```

Notice that we now can see observation #3's decimal places.

If we don't care to see the decimal place (even though it is still there).
```{stata for3, eval=FALSE}
format income %7.0f
list income in 1/5
```

```{stata for3_1, echo=FALSE}
quietly {
cd "/Users/Sam/Desktop/Econ 645/Data/Mitchell"
use survey5, clear
format income %12.2f
}
format income %7.0f
list income in 1/5
```

We we want to see one decimal place
```{stata for4, eval=FALSE}
format income %9.1f
list income in 1/5
```

```{stata for4_1, echo=FALSE}
quietly {
cd "/Users/Sam/Desktop/Econ 645/Data/Mitchell"
use survey5, clear
format income %12.2f
format income %7.0f
}
format income %9.1f
list income in 1/5
```

Now let's add commas, but we need to add two additional digit widths for the commas and we'll add two decimal places.
```{stata for5, eval=FALSE}
format income %12.2fc
list income in 1/5
```

```{stata for5_1, echo=FALSE}
quietly {
cd "/Users/Sam/Desktop/Econ 645/Data/Mitchell"
use survey5, clear
format income %12.2f
format income %7.0f
format income %9.1f
}
format income %12.2fc
list income in 1/5
```

### Format Strings

Let's use the *format* command with strings.
```{stata for6, eval=FALSE}
describe kidname
```

```{stata for6_1, echo=FALSE}
quietly {
cd "/Users/Sam/Desktop/Econ 645/Data/Mitchell"
use survey5, clear
}
describe kidname
```

The format is *%10s*, which is a (s)tring of 10 characters wide that is right-justified.
```{stata for7, eval=FALSE}
list kidname
```

```{stata for7_1, echo=FALSE}
quietly {
cd "/Users/Sam/Desktop/Econ 645/Data/Mitchell"
use survey5, clear
}
list kidname
```

If we wanted to left-justify the string, we can add a '-' in between % and #s.
```{stata for8, eval=FALSE}
format kidname %-10s
list kidname
```

```{stata for8_1, echo=FALSE}
quietly {
cd "/Users/Sam/Desktop/Econ 645/Data/Mitchell"
use survey5, clear
}
format kidname %-10s
list kidname
```


### Format dates

Dates in Stata are a bit of a pain, so learning how to format the dates will be helpful in the future.
```{stata date1, eval=FALSE}
list bdays kbdays
```

```{stata date1_1, echo=FALSE}
quietly {
cd "/Users/Sam/Desktop/Econ 645/Data/Mitchell"
use survey5, clear
}
list bdays kbdays
```

Our birthdays are in a MM/DD/YYYY format currently. Let's generate a new variable with the *date* function. The *date* function will convert a string that is in a date format into a Stata date, but it still needs to be formatted. The option "MDY" tells Stata that the string is in the Month-Day-Year format and needs to be converted.
```{stata date2, eval=FALSE}
generate bday = date(bdays, "MDY")
generate kbday = date(kbdays, "MDY")
```

Let's list the days.
```{stata date3, eval=FALSE}
list bdays bday kbdays kbday
```

```{stata date3_1, echo=FALSE}
quietly {
cd "/Users/Sam/Desktop/Econ 645/Data/Mitchell"
use survey5, clear 
generate bday = date(bdays, "MDY")
generate kbday = date(kbdays, "MDY")
}
list bdays bday kbdays kbday
```

The Stata dates are actually stored as the number of days from Jan 1, 1960. This method is convenient for the computer storing and performing date computations, but is difficult for us to read.

Let's use the *%td* format - for example 01Jan2000
```{stata date4, eval=FALSE}
format bday %td 
list bdays bday kbdays kbday
```

```{stata date4_1, echo=FALSE}
quietly {
cd "/Users/Sam/Desktop/Econ 645/Data/Mitchell"
use survey5, clear 
generate bday = date(bdays, "MDY")
generate kbday = date(kbdays, "MDY")
}
format bday %td 
list bdays bday kbdays kbday
```

Let's use the *%tdNN/DD/YY* format...*NN* is used for 01-12 and *nn* is for 1-12,*DD* for the day 01-31, and *YY* is for the last two digits of the year.
```{stata date5, eval=FALSE}
format bday %tdNN/DD/YY
list bdays bday kbdays kbday
```

```{stata date5_1, echo=FALSE}
quietly {
cd "/Users/Sam/Desktop/Econ 645/Data/Mitchell"
use survey5, clear 
generate bday = date(bdays, "MDY")
generate kbday = date(kbdays, "MDY")
}
format bday %tdNN/DD/YY
list bdays bday kbdays kbday
```

*Mon* is Jan-Dec, and *Month* is January-December.
```{stata date5_5, eval=FALSE}
format bday %tdMonth/DD/YY 
list bdays bday kbdays kbday
```

```{stata date5_51, echo=FALSE}
quietly {
cd "/Users/Sam/Desktop/Econ 645/Data/Mitchell"
use survey5, clear 
generate bday = date(bdays, "MDY")
generate kbday = date(kbdays, "MDY")
}
format bday %tdMonth/DD/YY 
list bdays bday kbdays kbday
```

We can use a standard Month DD, YYYY with the format *%tdMonth_DD,CCYY*. Where *Month* is the full name of the month, *DD* is our days in digits, and *CC* is Century, such as 19- and 20- and *YY* is 2-digit year, such as -88, -97
```{stata date6, eval=FALSE}
format bday %tdMonth_DD,CCYY
list bdays bday kbdays kbday
```

```{stata date6_1, echo=FALSE}
quietly {
cd "/Users/Sam/Desktop/Econ 645/Data/Mitchell"
use survey5, clear 
generate bday = date(bdays, "MDY")
generate kbday = date(kbdays, "MDY")
}
format bday %tdMonth_DD,CCYY
list bdays bday kbdays kbday
```

Let's use a standard format, but don't use *YYYY* - it just repeats the 2-digit year twice.
```{stata date7, eval=FALSE}
format bday %tdNN/DD/YYYY
list bdays bday kbdays kbday
```

```{stata date7_1, echo=FALSE}
quietly {
cd "/Users/Sam/Desktop/Econ 645/Data/Mitchell"
use survey5, clear 
generate bday = date(bdays, "MDY")
generate kbday = date(kbdays, "MDY")
}
format bday %tdNN/DD/YYYY
list bdays bday kbdays kbday
```

Use *%tdNN/DD/CCYY* instead for the desired result.
```{stata date8, eval=FALSE}
format bday %tdNN/DD/CCYY
list bdays bday kbdays kbday

label variable bday "Date of birth of student"
label variable kbdays "Date of birth of child"
```

```{stata date8_1, echo=FALSE}
quietly {
cd "/Users/Sam/Desktop/Econ 645/Data/Mitchell"
use survey5, clear 
generate bday = date(bdays, "MDY")
generate kbday = date(kbdays, "MDY")
}
format bday %tdNN/DD/CCYY
list bdays bday kbdays kbday

label variable bday "Date of birth of student"
label variable kbdays "Date of birth of child"
```

bday and bdays are redundent and we'll only keep one.
```{stata date9, eval=FALSE}
drop bday kbdays
save survey6, replace
```

## Changing the order of variables in a dataset

I personally find reordering the order of variables with the *order* command to be useful. This is especially true when working with panel data. I like to order the panel data to have the cross-sectional unit first, such as personal id, firm id, etc.first and then have the time period second, so we have our N and T next to one another.

Let's pull our survey of graduate students and describe our dataset
```{stata order1}
cd "/Users/Sam/Desktop/Econ 645/Data/Mitchell"
use survey6, clear
describe
```

We might want to group our variables with similar types of variables. This can be helpful when you have a large dataset with hundreds of variables, such as the CPS.
```{stata order2, eval=FALSE}
order id gender race bday income havechild
describe
```

```{stata order2_1, echo=FALSE}
quietly{
cd "/Users/Sam/Desktop/Econ 645/Data/Mitchell"
use survey6, clear
}
order id gender race bday income havechild
describe
```
The variables that we leave off will remain in the same order as before after the new variables are moved to the left.

With the *before* option, we can move variable(s) before a defined variable. Let's move kidname before ksex
```{stata order3, eval=FALSE}
order kidname, before(ksex)
describe
```

```{stata order3_1, echo=FALSE}
quietly{
cd "/Users/Sam/Desktop/Econ 645/Data/Mitchell"
use survey6, clear
order id gender race bday income havechild
}
order kidname, before(ksex)
describe
```

We can move newly created variables with the before and after options with the generate command
```{stata order4, eval=FALSE}
generate STUDENTVARS = ., before(gender)
generate KIDSVARS = ., after(havechild)
describe
```

```{stata order4_1, echo=FALSE}
quietly{
cd "/Users/Sam/Desktop/Econ 645/Data/Mitchell"
use survey6, clear
order id gender race bday income havechild
order kidname, before(ksex)
}
generate STUDENTVARS = ., before(gender)
generate KIDSVARS = ., after(havechild)
describe
```

## Practice

Let's bring in the CPS
	use "/Users/Sam/Desktop/Econ 645/Data/CPS/jun23pub.dta", clear

  1. Generate a new variable from pemlr called employed where employed = 1 if the individual is employed (present or absent) and employed = 0 if the individual is unemployed. The value should be missing if the individual is not in the labor force.
  2. Label the variable "Currently employed".
  3. Label the values for 0 "Not employed" 1 "Employed" . "Not in the Labor Force".
  4. Move the variable after pemlr.
  5. Generate a date that appends hrmonth (month of interview), the string "12", and the hryear4 (year of interview). We use 12 because the week of the 12th is the reference period.
  6. Now format the date so it is like 06/12/2023

