# EGEN Command

## EGEN Computations across variables
The *egen* command is something that I miss in other statistical packages since it is so useful. We can do computation across columns or we can do computation across observations with *egen*

For computations across columns/variables, we can look at row means, row mins, row maxs, row missing, row nonmissing, etc. On a personal note, I do not use computations across variables too often. If you have have panel data set, it should be in a long-form format instead of a wide-form format. When you use data in a long-form format, *egen* across variables has limited uses.

Let's find the mean across pl1-pl5 with <i>row mean</i> instead of *gen avgpl=(pl1+...+pl5)/5*

```{stata row1}
cd "/Users/Sam/Desktop/Econ 645/Data/Mitchell/"
use "cardio2miss.dta", clear
egen avgpl=rowmean(pl1-pl5)
list id pl1-pl5 avgpl
```

*rowmeans()* will ignore the missing values. (I wish other statistical packages did this)
```{stata row2, eval=FALSE}
egen avgbp=rowmean(bp1-bp5)
list id bp1-bp5 avgbp
```
```{stata row3, echo=FALSE}
quietly {
cd "/Users/Sam/Desktop/Econ 645/Data/Mitchell/"
use "cardio2miss.dta", clear
egen avgpl=rowmean(pl1-pl5)
}
egen avgbp=rowmean(bp1-bp5)
list id bp1-bp5 avgbp
```

*rowmin()* returns the row minimum, while *rowmax()* returns the row maximum.
```{stata row4, eval=FALSE}
egen maxbp=rowmax(bp1-bp5)
egen minbp=rowmin(bp1-bp5)
list id bp1-bp5 avgbp maxbp minbp
```
```{stata row4_1, echo=FALSE}
quietly {
cd "/Users/Sam/Desktop/Econ 645/Data/Mitchell/"
use "cardio2miss.dta", clear
egen avgpl=rowmean(pl1-pl5)
egen avgbp=rowmean(bp1-bp5)
}
egen maxbp=rowmax(bp1-bp5)
egen minbp=rowmin(bp1-bp5)
list id bp1-bp5 avgbp maxbp minbp
```

We can find missing or not missing with the *rowmiss()* and *rownonmiss()*
```{stata row5, eval=FALSE}
	egen missbp = rowmiss(bp?)
```

**Note**: the *?* operator differs from the wildcard * operator. The *?* operator is a wildcard for 1 character in between so *bp?* will pick up bp1, bp2, bp3, bp4, and bp5, and *bp?* will exlude bpavg, bpmin, bpmax
Examples:
  1. <i>my*var</i> variables starting with my & ending with var with any number of other characters between.
  2. <i>my~var</i> one variable starting with my & ending with var with any number of other characters between.
  3. <i>my?var</i> variables starting with my & ending with var with one other character between.

Recap:
  1. *myvar* is just one variable
  2. *myvar* *thisvar* *thatvar* are three variables
  3. *myvar* are all variables starting with myvar
  4. <i>*var</i> are all variables ending with var
  5. *myvar1*-*myvar6* includes myvar1, myvar2, ..., myvar6
  6. *this*-*that* includes variables *this* through *that*, inclusive

## EGEN Computation across observations

*EGEN* and *bysort* are a powerful combination for working across groups
of observations. This can be very helpful when working with panel 
data or time series by groups.  We will sort by id and then time and
perform our egen commands
We have our egen *sum, egen total, egen max, egen min, egen mean* which will be the main egen commands.



Let's use *egen* to find the average for groups. *Egen* without a bysort will return the mean for the entire column, which may or may not be helpful. If we want a mean within a group (or an individual's panel data), we want to sort by groups (or individuals) first and then perform the egen mean.

```{stata col1}
cd "/Users/Sam/Desktop/Econ 645/Data/Mitchell/"
use "gasctrysmall.dta", clear
egen avggas = mean(gas)
bysort ctry: egen avggas_ctry = mean(gas)
list ctry year gas avggas avggas_ctry, sepby(ctry)
```

Let's get the *max* and *min* for each country. 
```{stata col2, eval=FALSE}
bysort ctry: egen mingas_ctry = min(gas)
bysort ctry: egen maxgas_ctry = max(gas)
```
```{stata col3, echo=FALSE}
quietly {
cd "/Users/Sam/Desktop/Econ 645/Data/Mitchell/"
use "gasctrysmall.dta", clear
egen avggas = mean(gas)
bysort ctry: egen avggas_ctry = mean(gas)
}
bysort ctry: egen mingas_ctry = min(gas)
bysort ctry: egen maxgas_ctry = max(gas)
```

We can count our observations. 
```{stata col4, eval=FALSE}
bysort ctry: egen count_ctry=count(gas)
list, sepby(ctry)
```
```{stata col5, echo=FALSE}
quietly {
cd "/Users/Sam/Desktop/Econ 645/Data/Mitchell/"
use "gasctrysmall.dta", clear
egen avggas = mean(gas)
bysort ctry: egen avggas_ctry = mean(gas)
bysort ctry: egen mingas_ctry = min(gas)
bysort ctry: egen maxgas_ctry = max(gas)
}
bysort ctry: egen count_ctry=count(gas)
list, sepby(ctry)
```

We also have *egen count()*, *egen iqr()*, *egen median()*, and *egen pctile(#,p(#))*
See more egen commands:
```{stata col6}
help egen
```

### Subscripting 
*(Head start to Mitchell 8.4)*

*Bysort* can be combined with indexes/subscripting to find the first, last, or #
observaration within a group
```{stata sub1,eval=FALSE}
cd "/Users/Sam/Desktop/Econ 645/Data/Mitchell/"
use "gasctrysmall.dta", clear
```

Find first year and last year
```{stata sub2,eval=FALSE}
bysort ctry: gen firstyr = year[1]
bysort ctry: gen lastyr = year[_N]
```
```{stata sub3, echo=FALSE}
quietly{
cd "/Users/Sam/Desktop/Econ 645/Data/Mitchell/"
use "gasctrysmall.dta", clear
}
bysort ctry: gen firstyr = year[1]
bysort ctry: gen lastyr = year[_N]
list, sepby(ctry)
```
Take a difference between periods (same as l.var)
```{stata sub4, eval=FALSE}
bysort ctry: gen diffgas = gas-gas[_n-1]
```
```{stata sub5, echo=FALSE}
quietly{
cd "/Users/Sam/Desktop/Econ 645/Data/Mitchell/"
use "gasctrysmall.dta", clear
bysort ctry: gen firstyr = year[1]
bysort ctry: gen lastyr = year[_N]
}
bysort ctry: gen diffgas = gas-gas[_n-1]
list, sepby(ctry)
```
Create Indexes for Rate of change to base year
```{stata sub6, eval=FALSE}
bysort ctry: gen gasindex = gas/gas[1]*100
```
```{stata sub7, echo=FALSE}
quietly{
cd "/Users/Sam/Desktop/Econ 645/Data/Mitchell/"
use "gasctrysmall.dta", clear
bysort ctry: gen firstyr = year[1]
bysort ctry: gen lastyr = year[_N]
bysort ctry: gen diffgas = gas-gas[_n-1]
}
bysort ctry: gen gasindex = gas/gas[1]*100
list, sepby(ctry)
```
### More Egen

This section has more interesting egen commands that you can review if you would like. The workhorse egen commands are above.


## Converting Strings to numerics

These next two section have a lot of practical implications that you find when working with survey and especially administrative data. First we will cover converting numerical characters in strings to numerical data to analyze.


Let's summarize our data, but it comes back blank.
```{stata con1}
cd "/Users/Sam/Desktop/Econ 645/Data/Mitchell"
use "cardio1str.dta", clear
sum wt bp1 bp2 bp3
```

All of our numerical data are in string formats.
```{stata con2, eval=FALSE}
describe
```
```{stata con3, echo=FALSE}
quietly {
cd "/Users/Sam/Desktop/Econ 645/Data/Mitchell"
use "cardio1str.dta", clear
}
describe
```

### Destring

The *destring* command is our main command to convert numerical characters to numerics. With *destring*, we have to choose an option of generating a new variable or replace the current variable
```{stata con4, eval=FALSE}
destring age, gen(agen)
sum age agen
drop agen
```
```{stata con5, echo=FALSE}
quietly {
cd "/Users/Sam/Desktop/Econ 645/Data/Mitchell"
use "cardio1str.dta", clear
}
destring age, gen(agen)
sum age agen
drop agen
```

We can destring all of our numerics.
```{stata con6, eval=FALSE}
destring id-income, replace
```
```{stata con7, eval=FALSE}
quietly {
cd "/Users/Sam/Desktop/Econ 645/Data/Mitchell"
use "cardio1str.dta", clear
}
destring id-income, replace
```

Notice that the replace failed for income and pl3. This is becuase pl3 has a letter, so all of the data are not all digits. Income has $ and , so it can not convert the data.

We can use the force option with pl3 to convert the X to missing.
```{stata con8, eval=FALSE}
list pl3
destring pl3, replace force
list pl3
```
```{stata con9, echo=FALSE}
quietly {
cd "/Users/Sam/Desktop/Econ 645/Data/Mitchell"
use "cardio1str.dta", clear
destring id-income, replace
}
list pl3
destring pl3, replace force
list pl3
```

We cannot use the force option with income, since it contains important information. We need to get rid of the two non-numerical characters of $ and ,

We have two options: eliminate the "$" and "," or use the ignore option in destring. The latter option is easier.
```{stata con10, eval=FALSE}
list income
destring income, replace ignore("$,")
list income
```

```{stata con11, echo=FALSE}
quietly {
cd "/Users/Sam/Desktop/Econ 645/Data/Mitchell"
use "cardio1str.dta", clear
destring id-income, replace
destring pl3, replace force
}
list income
destring income, replace ignore("$,")
list income
```

### Encode

Sometimes we have categorical variables or ID variables that come in as strings. We need to code them as categorical, but strings can be tricky with leading or lagging zeros or misspellings.

One option is to use the *encode* command, which will generate a new variable that codifies the string variable. This can be very helpful when our id variable in panel data are in string format.

Remember: trim any white space around the string just in case, 
  1. *strtrim()* - remove leading and lagging white space
  2. *strrtrim()* - removes lagging white spaces
  3. *strltrim()* - removes leading white spaces
  4. *stritrim()* - removes leading, lagging, and consecutive white spaces

```{stata con12, eval=FALSE}
list id gender
replace gender = stritrim(gender)
encode gender, generate(gendercode)
list gender gendercode
```
```{stata con13, echo=FALSE}
quietly {
cd "/Users/Sam/Desktop/Econ 645/Data/Mitchell"
use "cardio1str.dta", clear
destring id-income, replace
destring pl3, replace force
destring income, replace ignore("$,")
}
list id gender
replace gender = stritrim(gender)
encode gender, generate(gendercode)
list gender gendercode
```
They look the same, but let's use tabulation

```{stata con14, eval=FALSE}
tab gender gendercode, nolabel
```
```{stata con15, echo=FALSE}
quietly {
cd "/Users/Sam/Desktop/Econ 645/Data/Mitchell"
use "cardio1str.dta", clear
destring id-income, replace
destring pl3, replace force
destring income, replace ignore("$,")
replace gender = stritrim(gender)
encode gender, generate(gendercode)
}
tab gender gendercode, nolabel
```
The encode creates label values around the new variable
```{stata con16, eval=FALSE}
codebook gendercode
```
```{stata con17, echo=FALSE}
quietly {
cd "/Users/Sam/Desktop/Econ 645/Data/Mitchell"
use "cardio1str.dta", clear
destring id-income, replace
destring pl3, replace force
destring income, replace ignore("$,")
replace gender = stritrim(gender)
encode gender, generate(gendercode)
}
codebook gendercode
```

### Converting numerics to strings
In my experience, it is more common to *destring*, but there are situtations where you need to convert a numeric to a string. The most common examples from me are zip codes and FIPS codes. We use the *tostring* command for this process.

As a side note, whenever working with or merging with state-level **data, always, always** use FIPS codes and not state names or state abbreviations. The probability of a problematic merge is much higher matching on strings than it is on numerics.

```{stata con18}
cd "/Users/Sam/Desktop/Econ 645/Data/Mitchell/"
use "cardio3.dta", clear
list zipcode
```

This zip code list is a problem and likely will not merge properly, since zipcodes that have a leading 0 will not match.
```{stata con19, eval=FALSE}
tostring zipcode, generate(zips)
replace zips = "0" + zips if strlen(zips) == 4
replace zips = "00" + zips if strlen(zips) == 3
list zipcode zips
```
```{stata con20, echo=FALSE}
quietly {
cd "/Users/Sam/Desktop/Econ 645/Data/Mitchell/"
use "cardio3.dta", clear
}
tostring zipcode, generate(zips)
replace zips = "0" + zips if strlen(zips) == 4
replace zips = "00" + zips if strlen(zips) == 3
list zipcode zips
```
I don't recommend just formatting the data to 5 digits. The data should be formatted exactly for matching and merging between datasets on the key merging variable.

I recommend using *tostring*, but there is decode which is the opposite of *encode*. If we want to use the variable labels instead of the numeric for some reason, the *decode* command can be used.

```{stata con21, eval=FALSE}
decode famhist, gen(famhists)
list famhist famhists, nolabel
codebook famhist famhists
```
```{stata con22, echo=FALSE}
quietly {
cd "/Users/Sam/Desktop/Econ 645/Data/Mitchell/"
use "cardio3.dta", clear
tostring zipcode, generate(zips)
replace zips = "0" + zips if strlen(zips) == 4
replace zips = "00" + zips if strlen(zips) == 3
}
decode famhist, gen(famhists)
list famhist famhists, nolabel
codebook famhist famhists
```

## Renaming and reordering

Reordering and renaming seems straightforward enough, but there are some useful tips that will help consolidate your scripts. For example, you don't need to a new rename command for every single variable to be renamed. We can use group renaming.



### Rename

The rename command is straightfoward, and allows us to rename
our variable(s) of interest.
```{stata ren1}
cd "/Users/Sam/Desktop/Econ 645/Data/Mitchell/"
use "cardio2.dta", clear
describe
rename age age_yrs
describe
```

We also can do bulk renames if the group of variables have common
characters in the variable name. We can rename our pl group to pulse
```{stata ren2, eval=FALSE}
rename pl? pulse? 
describe
```
```{stata ren3, echo=FALSE}
quietly {
cd "/Users/Sam/Desktop/Econ 645/Data/Mitchell/"
use "cardio2.dta", clear
rename age age_yrs
}
rename pl? pulse? 
describe
```
Where ? is an operator for just one character to be different.


An alternate way is to rename by grouping and it prevents any unintended renaming with the ? or * operators.
```{stata ren4, eval=FALSE}
rename (bp1 bp2 bp3 bp4 bp5) (bpress1 bpress2 bpress3 bpress4 bpress5)
describe
```
```{stata ren5, echo=FALSE}
quietly {
cd "/Users/Sam/Desktop/Econ 645/Data/Mitchell/"
use "cardio2.dta", clear
rename age age_yrs
rename pl? pulse? 
}
rename (bp1 bp2 bp3 bp4 bp5) (bpress1 bpress2 bpress3 bpress4 bpress5)
describe
```


### Order

We can move our variables around with the *order* command. This command can be especially helpful with panel data, since we want the unit id and the time period to be next to one another.

Our variables are out of order and pl and bp alternate, but we may want to keep our pl variables and bp variables next to one another.

Reorder blood pressure and pulse

```{stata ren6, eval=FALSE}
order id age_yrs bp* pul*
```  
```{stata ren7, echo-FALSE}
quietly {
cd "/Users/Sam/Desktop/Econ 645/Data/Mitchell/"
use "cardio2.dta", clear
rename age age_yrs
rename pl? pulse? 
rename (bp1 bp2 bp3 bp4 bp5) (bpress1 bpress2 bpress3 bpress4 bpress5)
}
order id age_yrs bp* pul*
```
Or,
```{stata ren8, eval=FALSE}
order pul* bp*, after(age_yrs) 
```
Or,
```{stata ren9, eval=FALSE}
order bp*, before(pulse1)
```

If you generate a new variable, it will default to the end, but we may want it somewhere else. Let's say we want age-squared, but we want age-squared to be next to age. We can use the *after* (or before) option in the *generate* command.
```{stata ren10, eval=FALSE}
gen age2=age_yrs*age_yrs, after(age_yrs)
```
If you wanted to reorder the whole dataset alphabetically, then
```{stata ren11, eval=FALSE}
order _all, alphabetic
describe
```
```{stata ren12, echo=FALSE}
quietly{
cd "/Users/Sam/Desktop/Econ 645/Data/Mitchell/"
use "cardio2.dta", clear
rename age age_yrs
rename pl? pulse? 
rename (bp1 bp2 bp3 bp4 bp5) (bpress1 bpress2 bpress3 bpress4 bpress5)
gen age2=age_yrs*age_yrs, after(age_yrs)  
}
order _all, alphabetic
describe
```
There is a sequential option as well if your var1, ..., vark are out of order
```{stata ren13, eval=FALSE}
order bpress5 bpress1-bpress4, after(age2)
describe
order bp*, sequential
describe
```
```{stata ren13_1, echo=FALSE}
quietly {
cd "/Users/Sam/Desktop/Econ 645/Data/Mitchell/"
use "cardio2.dta", clear
rename age age_yrs
rename pl? pulse? 
rename (bp1 bp2 bp3 bp4 bp5) (bpress1 bpress2 bpress3 bpress4 bpress5)
gen age2=age_yrs*age_yrs, after(age_yrs)
order id age_yrs bp* pul*
}
order bpress5 bpress1-bpress4, after(age2)
describe
order bp*, sequential
describe
```
