# Exercises

## General Social Survey

What is the relationship between years of education and hours worked using the 2006 General Social Survey? Read in the file called "gss2006_chapter8.dta".

Steps

  1. What is the relationship between hours worked last week and years of education?
  2. Use *sum* to inspect the data for hours worked last week and years of education.
  3. Do you notice any differences?
  4. What is the mean and median of both variables?
  5. What is the covariance? Interpret the result. (Do they move together?)
  6. Next run a casewise deletion using the command *correlate*
  7. Interpret the results about the relationship.
  
Steps

  1. Let's graph the two variables *hrs1* and *educ* from the prior steps
  2. Use *twoway (scatter v1 v2)* to graph the two variables without *jitter(#)*.
  3. What do you notice? Can you tell if there is a relationship? 
  4. Let's rerun *twoway (scatter v1 v2)* but add the *jitter(#)* option.
  5. Is the issue still present? Can you tell if there is a relationship?
  6. Let's use the *binscatter*.
  7. Is this a clearer graph? If so, what about the data structure of *educ* lends itself to this?
  8. Interpret the relationship.
  9. How does opportunity cost help explain the relationship?
  
Steps

  1. What is the relationship between happiness and health?
  2. Use the *fre1*, *tab1*, or *tabulate* commands to inspect the variables *happy*,*hapmar*, and *health*.
  3. What do you notice about the missing observations? Why is *hapmar* missing variables so high?
  4. Question to ponder: Why are there 2000+ missing observations and is it possible that non response is related to health and happiness? 
  5. Let's do a casewise deletion correlation with the *pwcorr* command. Use the *obs* option to check the number of observations used to calculate the correlations.
  6. Interpret the results.
  7. Let's use a pairwise deletion with the *pwcorr* command. Use the *obs* option.
  8. What do you notice between the pairwise and casewise? Do the results differ?
  9. Rerun the pairwise correlations, but test for statistical significance.
  10. Seeing these results is it possible we have a "chicken-and-the-egg" problem, or more formally, an endogeneity problem?
   
## Annual Survey of Manufacturers 2012-2018

We will inspect the relationships in manufacturing production. We will read in the file called "nberces_2012_2018.dta" on ELMS. The data can also be found on NBER's website: https://www.nber.org/research/data/nber-ces-manufacturing-industry-database

This data set includes manufacturing data from 2012-2018 for 6-digit (most detailed) North American Industry Classification System (NAICS) from Becker, et al. (2026). We'll use these data for Econ 642 for \( Y = f(K,L) \)

Steps

  1. What is the relationship between value-added output, capital, and labor?
  2. Read in the data set called "nberces_2012_2018.dta"
  2. Let's inspect *vadd* *cap* *prodh* with the *summarize* command
  4. Use a pairwise correlation for *vadd* *cap* *prodh*
  5. Interpret the relationships.
  6. 

Next we will graph the relationships.

  1. Use a scatter plot for both *vadd* and *cap* and *vadd* and *prodh*
  2. What do you notice about the shapes of the graphs?
  3. Use a scatter plot for *cap* and *vadd*
  4. Do you notice anything interesting? Think about the Inada Conditions:  \( lim_{K\rightarrow \infty}F_K(K,L)=0 \) and  \( lim_{K\rightarrow 0}F_K(K,L)=\infty \)
  5. Use a binscatter for for both *vadd* and *cap* and *vadd* and *prodh*
  6. Interpret the graphs.


