# Exercises

## Current Population Survey

We will work with the raw data public use micro data from the Current Population Survey. The July 2026 data can be found here: https://www.census.gov/data/datasets/time-series/demo/cps/cps-basic.html


For creating variables and labeling data, we will need the data dictionary: https://www2.census.gov/programs-surveys/cps/datasets/2026/basic/2026_Basic_CPS_Public_Use_Record_Layout_plus_IO_Code_list.txt

Steps

  1. Import the csv file
  2. Generate a binary variable called *female*, based on *pesex*
  3. Label the variable "Individual is female"
  4. Label the values 0 "Male" and 1 "Female"
  5. Tabulate the results to make sure all values were correctly categorized
  
Steps

  1. Generate a nominal categorical variable called *race* based on *ptdtrace* and *pehspnon*.
  2. Label the variable "Individual's race/ethnicity"
  3. Label the values 1 "Non-Hispanic White" 2 "Non-Hispanic Black" 3 "Non-Hispanic AIAN" 4 "Non-Hispanic Asian" 5 "Non-Hispanic NHOPI" 6 "Latino/a" 7 "Non-Hispanic Multiracial"
  4. Tabulate the results to make sure all values were correctly categorized

Steps

  1. Generate a binary variable called *union* based on *peernlab*
  2. Label the variable "Union member status"
  3. Label the values 0 "Not a union member" 1 "Union member"
  4. Tabulate the results to make sure all values were correctly categorized
  
Steps

  1. Generate a continuous variable called earnings
  2. Divide the variable by *pternwa* by 100
  3. Label the variable "Weekly earnings"
  4. Summarize the variable
  5. Summarize the variable again but with the qualifier that *prerelg==1*
  6. Generate a histogram with the qualifier
  7. Compare weekly earnings among race, sex, and union members with the *table* command
  8. What is the unweighted mean weekly earnings for a unionized non-Hispanic multiracial female and a non-unionized non-Hispanic multiracial female?