# Reshape

From my experience, I feel that understanding and mastering the reshape command is invaluable. This is especially true when working with panel data. Panel data should not be used in a wide format. Panel data should be in a long format where you can use the xtset unit time command. After the xtset is established you can easily add lags or differences with the l.var or d.var

It is also helpful in terms of merging datasets. A lot of time if I'm merging BLS data, such as state unemployment, or inflation rates, I need to reshape the BLS data from wide to long to I can merge m:1 

I typically work in long formats, but reshaping to wide formats does have its benefits. I find wide formats are helpful for people who work in excel, especially when years are across columns.

## Wide and Long Datasets

We have two types of datasets: wide and long

### Wide Format {-}

Our wide datasets typically include years or variables types spread out across
the columns. 
```{stata wide1}
cd "/Users/Sam/Desktop/Econ 645/Data/Mitchell"
use cardio_wide, clear
describe
```

We have 12 variables idcode, age, and our 5 different blood pressure and pulse trials. We see that are 5 different incidents/trials of blood pressure and pulse are spread out across 5 different variables \( bp1-bp5 \) and \( pl1-pl5 \)*
```{stata wide2, eval=FALSE}
list
```

```{stata wide2_1, echo=FALSE}
quietly {
cd "/Users/Sam/Desktop/Econ 645/Data/Mitchell"
use cardio_wide, clear
}
list
```

With a wide format each row is an observation and all of our different trials are located on a single row

### Long Format {-}

We'll look at an example of the same dataset but in long format
```{stata long1}
cd "/Users/Sam/Desktop/Econ 645/Data/Mitchell"
use cardio_long, clear
describe
```

We only have 5 variables idcode, age, trial, blood pressure, and pulse.
```{stata long2, eval=FALSE}
list
```

```{stata long2_1, echo=FALSE}
quietly {
cd "/Users/Sam/Desktop/Econ 645/Data/Mitchell"
use cardio_long, clear
}
list
```


We also see that each individual has 5 observations. One for each trial that is sorted from 1 to 5. 

**Notice:**
We have a cross-sectional unit variable with \( idcode \) and we also have a time component with \( trial \). Our dataset is basically a panel data set. We observe the same person over 5 trials.

What kind of format should we use? 

It depends.

### Wide Format {-}
Mitchell makes a good point of looking at correlations among the blood pressure trials. 
```{stata wide3}
cd "/Users/Sam/Desktop/Econ 645/Data/Mitchell"
use cardio_wide, clear
correlate bp1 bp2 bp3 bp4 bp5
```

Mitchell also mentions that multivariate analysis with multiple trials is a bit easier with factor variables. If we wanted to see all of the different regressions for each trial, then 
```{stata wide4, eval=FALSE}
mvreg bp* = age
```

```{stata wide4_1, echo=FALSE}
quietly {
cd "/Users/Sam/Desktop/Econ 645/Data/Mitchell"
use cardio_wide, clear
}
mvreg bp* = age
```

### Long Format {-}

There are several reasons we would want to use long format over wide format

#### Correlations {-}
If we want correlations between blood pressure and pulse, a long format is preferable.
```{stata long3}
cd "/Users/Sam/Desktop/Econ 645/Data/Mitchell"
use cardio_long, clear
correlate bp pl
```

Or
```{stata long4, eval=FALSE}
bysort trial: correlate bp pl
```

```{stata long4_1, echo=FALSE}
quietly {
cd "/Users/Sam/Desktop/Econ 645/Data/Mitchell"
use cardio_long, clear
}
bysort trial: correlate bp pl
```

#### Panel data {-}

It is also more appropriate for panel data and the xt commands, such as *xtset*, *xtreg*, etc. I also prefer this for regular regressions where we can use factor variables \( i.var \) for different time periods.
```{stata long5, eval=FALSE}
xtset id trial
xtreg bp age
xtline bp, overlay
```

#### Recoding {-}

It is also easier to recode in long format.
```{stata long6, eval=FALSE}
recode pl (min/89=0) (90/max=1), generate (plhi)
```

Recoding among many variables in wide format is more of a pain
You can see this on page 293 in Mitchell. 

#### Egen is easier {-}

If you wanted to mean of each 5 trials, it just as easy with egen in long format.
```{stata long7, eval=FALSE}
bysort id: egen pl_avg=mean(pl)
bysort id: egen bp_avg=mean(bp)
```

For wide-format you can use rowmean with the wildcard
```{stata long8, eval=FALSE}
use cardio_wide, clear
```

We don't need the bysort group, but we need to be careful which columns to include
```{stata long9, eval=FALSE}
egen pl_avg = rowmean(pl*)
egen bp_avg = rowmean(bp*)
```

It easier to explicitly difference trails with wide-format, but requires more typing.
```{stata long10, eval=FALSE}
generate pldiff2 = pl2-pl1
generate pldiff3 = pl3-pl2
generate pldiff4 = pl4-pl3
generate pldiff5 = pl5-pl4
```

#### Using subscripting/indexing, differences, lags with ease

I prefer using subscripting/indexing within groups or using xtset with panel data since we have a lot of flexibilities.
```{stata sub1, eval=FALSE}
cd "/Users/Sam/Desktop/Econ 645/Data/Mitchell"
use cardio_long, clear
sort id trial
```

We can use indexing 
```{stata sub2, eval=FALSE}
by id: generate pldiff = pl-pl[_n-1]
```

We can difference from the first trial
```{stata sub3, eval=FALSE}
by id: generate pldiff_1trial = pl-pl[1]
```
We can use xtset as well with l.var
```{stata sub4, eval=FALSE}
xtset id trial
```

```{stata sub4_1, echo=FALSE}
quietly {
cd "/Users/Sam/Desktop/Econ 645/Data/Mitchell"
use cardio_long, clear
sort id trial 
by id: generate pldiff = pl-pl[_n-1]
by id: generate pldiff_1trial = pl-pl[1]
}
xtset id trial
```

One lag
```{stata sub5, eval=FALSE}
gen pldiff_other = pl-l.pl
```

We can use two lags
```{stata sub6, eval=FALSE}
gen pldiff2_other = l2.pl-l1.pl
```

We can use three lags
```{stata sub7, eval=FALSE}
gen pldiff3_other = l3.pl-l2.pl
list
```

```{stata sub7_1, echo=FALSE}
quietly {
cd "/Users/Sam/Desktop/Econ 645/Data/Mitchell"
use cardio_long, clear
sort id trial 
xtset id trial
by id: generate pldiff = pl-pl[_n-1]
by id: generate pldiff_1trial = pl-pl[1]
gen pldiff_other = pl-l.pl
gen pldiff2_other = l2.pl-l1.pl
}

gen pldiff3_other = l3.pl-l2.pl
list
```
  
Wide format can become unwieldy quickly and Stata does have a variable limit size, while your observation limit is typically your memory.In short, it is better in the long-run to learn to work with Stata in long-format.

However, Mitchell does bring up a good point that in our panel data, we mayneed multiple weights wt1-wtk. You can see this in the ACS PUMS with 250 or soreplicate weights. We do not want to reshape our data by weights, we need to keep the data in a cross-sectional unit i and time period t format.

In short, I agree with Mitchell that you should learn to work with your data in a long-format data structure.

## Reshaping Long to Wide

There may be scenarios where we need to reshape our long-format data into
a wide format. For example, it might be easier to match and merge our data
If our using data set is in wide format and our master data set is in wide
format

Let's look at an example
```{stata reshape1}
cd "/Users/Sam/Desktop/Econ 645/Data/Mitchell"
use cardio_long, clear
describe 
list
```

Our reshape command requires *reshape*
  1. What direction: wide or long
  2. Variables to reshape (bp and pl)
  3. Variables define an observation i(id)
  4. Variables that defines the repeated observations for each person orvtime variable j(trial) for reshaping long to wide
  
Trial values will become the suffix values for our reshape values
```{stata reshape2, eval=FALSE}
reshape wide bp pl, i(id) j(trial)
describe
list
```

```{stata reshape2_1, echo=FALSE}
quietly {
cd "/Users/Sam/Desktop/Econ 645/Data/Mitchell"
use cardio_long, clear
}
reshape wide bp pl, i(id) j(trial)
describe
list
```

Notice we excluded age. It is constant within the cross-sectional unit. It does not define the cross-sectional unit or the*time dimension unit. We do not want to separate it into repeated observations either.

Without doing any additional work, we can reshape it back to long with simply reshape long.
```{stata reshape3, eval=FALSE}
reshape long
describe
```

```{stata reshape3_1, echo=FALSE}
quietly {
cd "/Users/Sam/Desktop/Econ 645/Data/Mitchell"
use cardio_long, clear
reshape wide bp pl, i(id) j(trial)
}
reshape long
describe
```

## Reshaping Long to Wide: Problems

### Problem 1: A constant value within a cross-sectional unit is not constant {-} 
```{stata problem1}
cd "/Users/Sam/Desktop/Econ 645/Data/Mitchell"
use cardio_long2, clear
list in 1/10
```
We see that cross-sectional unit 1 has a data entry problem with age in the 3rd trial. If we reshape, we will get an error
```{stata problem2, eval=FALSE}
reshape wide bp pl, i(id) j(trial)
```

```{stata problem2_1, echo=FALSE}
quietly{
cd "/Users/Sam/Desktop/Econ 645/Data/Mitchell"
use cardio_long2, clear 
}
reshape wide bp pl, i(id) j(trial)
```

Use the reshape error command to help with the problem
```{stata problem3, eval=FALSE}
reshape error
```
It tells us that our constant variable is not constant within cross-sectional units.

### Problem 2: Excluding a non-constant that we need to reshape {-} 

If we excluded pl from our reshape, we will get a similar error.
```{stata problem4, eval=FALSE}
capture reshape wide bp, i(id) j(trial)
reshape error
```

```{stata problem4_1, echo=FALSE}
quietly{
cd "/Users/Sam/Desktop/Econ 645/Data/Mitchell"
use cardio_long2, clear 
}
capture reshape wide bp, i(id) j(trial)
reshape error
```

## Reshaping Wide to Long

In my personal opinion, this reshaping wide to long is a more common occurance. It is important to get data into a long-format so we can conduct panel analysis. I had to do this for a few of the Wooldridge datasets that were panel data, but in wide format.
```{stata wide_2_long1}
cd "/Users/Sam/Desktop/Econ 645/Data/Mitchell"
use cardio_wide, clear
describe
list
```

Let's reshape wide to long. 

Our reshape values that are not constant: bp and pl.

Our cross-sectional unit to reshape upon or our list of variables that uniquely identify a cross-sectional unit. For example, we may need a State FIPS code and a County FIPS code to unique identify a county 
cross-sectional unit (of course we can merge the 2-digit State FIPS code and the 3-digit County FIPS code to create a 5-digit FIPS code in one variable).

Our time unit, where with reshape long, we need to create a new variable that takes on the values of the suffixes of bp and pl (For example trialnum). Our constant values within cross-sectional units do not need to be identified. 
```{stata wide_2_long2, eval=FALSE}
reshape long bp pl, i(id) j(trialnum)
describe
list in 1/10
```

```{stata wide_2_long2_1, echo=FALSE}
quietly {
cd "/Users/Sam/Desktop/Econ 645/Data/Mitchell"
use cardio_wide, clear
}
reshape long bp pl, i(id) j(trialnum)
describe
list in 1/10
```
To reshape it back to wide, we just simply state
```{stata wide_2_long3, eval=FALSE}
reshape wide
describe
list
```

```{stata wide_2_long3_1, echo=FALSE}
quietly {
cd "/Users/Sam/Desktop/Econ 645/Data/Mitchell"
use cardio_wide, clear
reshape long bp pl, i(id) j(trialnum)
}
reshape wide
describe
list
```

## Reshaping wide to long problems

### Problem 1: Failing to list all of the varying variables to be reshaped. {-}

This is a dangerous kind of problem, since it doesn't throw an error.
This requires the user to inspect the data after reshaping to make sure
everything worked properly.
```{stata problem5}
cd "/Users/Sam/Desktop/Econ 645/Data/Mitchell"
use cardio_wide, clear
reshape long bp, i(id) j(trialnum)
list
```

The remedy is easy: don't forget all of your variables to be reshaped
```{stata problem6, eval=FALSE}
use cardio_wide, clear
reshape long bp pl, i(id) j(trialnum)
```

### Problem 2: Be careful when the time-varying value is embedded within the variable name and not at the end. {-}

Typically you will find that the varying variable will have \( var_1, var_2, ..., var_k \) and you simply specify reshape long var, i(id) j(time). But, if the varying value is embedded like t1bp,...,t5bp and t1pl,...,t5pl, then we cannot simply use reshape long tbp tpl, i(id) j(trialnum), since Stata looks for the varying value at the end.
```{stata problem7}
cd "/Users/Sam/Desktop/Econ 645/Data/Mitchell"
use cardio_wide2, clear
describe
capture reshape long tpl tpb, i(id) j(trialnum)
reshape error
```

We need the operator @ to indicate to Stata that our varying-values are in
that part of the variable names.
```{stata problem8, eval=FALSE}
reshape long t@pl t@bp, i(id) j(trialnum)
describe
list in 1/10
```

```{stata problem8_1, echo=FALSE}
quietly {
cd "/Users/Sam/Desktop/Econ 645/Data/Mitchell"
use cardio_wide2, clear
}
reshape long t@pl t@bp, i(id) j(trialnum)
describe
list in 1/10
```

### Problem 3: Be specific with which variables to reshape and don't mistakenly constant variables that have the same prefix as the varying variables {-}

```{stata problem9}
cd "/Users/Sam/Desktop/Econ 645/Data/Mitchell"
use cardio_wide3, clear
clist bp* pl*, noobs
```

Our \( bp2005 \) and \( pl2005 \) are constant variables within our cross-section, but have the same prefix as our value-varying variables.
```{stata problem10, eval=FALSE}
reshape long bp pl, i(id) j(trialnum)
describe
list in 1/12, sepby(id)
```

```{stata problem10_1, echo=FALSE}
quietly {
cd "/Users/Sam/Desktop/Econ 645/Data/Mitchell"
use cardio_wide3, clear
}
reshape long bp pl, i(id) j(trialnum)
describe
list in 1/12, sepby(id)
```

We did not intend to reshape \( bp2005 \) and \( pl2005 \). 

To rememdy, we need to specify the values within j() with j(trialnum 1-5) to indicate that we only want to reshape suffixes with 1-5.
```{stata problem11}
cd "/Users/Sam/Desktop/Econ 645/Data/Mitchell"
use cardio_wide3, clear
reshape long bp pl, i(id) j(trialnum 1-5)
describe
list in 1/10, sepby(id)
```

### Problem 4: No id varible to identify the cross-sectional unit {-}
If each wide-format observation is a unique cross-sectional unit, then we can use _n to generate a unique id variable.
```{stata problem12}
cd "/Users/Sam/Desktop/Econ 645/Data/Mitchell"
use cardio_wide3, clear
describe
gen idcode = _n
describe
reshape long bp pl, i(id idcode) j(trialnum 1-5)
describe
list in 1/10, sepby(id)
```

## Multilevel datasets

Mitchell discusses when we have multiple levels of data, such as cross-sectional unit i and time dimension t, where data is level 1 data are constant across time within unit, but vary across cross-sectional units and level 2 data are time-varying data that vary within a cross-sectional units

Sometimes we have multiple levels, such as school district, school, classroom, and student. 

If you are interested, please review pages 311-314

## Collapsing datasets

The *collapse* command can be useful finding statistics at aggregate levels for different groups.  You don't have to use egen but you can if you would like. After using the egen command, such as egen sumvar = sum(var), 
or egen avgvar = mean(var) the *collapse* command can be useful. 

Let's say we want to aggregate mean wages by state in the CPS, we can use the *egen mean* command to find average wages in the state for month m in year y. We can then keep state month year and avgvar for all 50 states for each
month and year of interest.

We need to be careful with the collapse command, since your original data are lost from memory unless you use a tempfile or a data frame.

```{stata collapse1}
cd "/Users/Sam/Desktop/Econ 645/Data/Mitchell"
use cardio_long, clear
list, sepby(id)
```

Let's say we want to find mean blood pressure and pluse for each cross-sectional unit, then we can use the egen command or the collapse commands.
```{stata collapse2, eval=FALSE}
sort id
by id: egen meanbp = mean(bp)
by id: egen meanpl = mean(pl)
by id: egen maxbp = max(bp)
by id: egen maxpl = max(bp)
by id: egen minbp = min(bp)
by id: egen minpl = min(bp)
by id: egen medbp = pctile(bp), p(50)
by id: egen medpl = pctile(pl), p(50)

collapse meanbp meanpl maxbp maxpl minbp minpl medbp medpl, by(id)
```

```{stata collapse2_1, echo=FALSE}
quietly {
cd "/Users/Sam/Desktop/Econ 645/Data/Mitchell"
use cardio_long, clear
}
sort id
by id: egen meanbp = mean(bp)
by id: egen meanpl = mean(pl)
by id: egen maxbp = max(bp)
by id: egen maxpl = max(bp)
by id: egen minbp = min(bp)
by id: egen minpl = min(bp)
by id: egen medbp = pctile(bp), p(50)
by id: egen medpl = pctile(pl), p(50)

collapse meanbp meanpl maxbp maxpl minbp minpl medbp medpl, by(id)
```

Or you can just use the collapse command
```{stata collapse3}
cd "/Users/Sam/Desktop/Econ 645/Data/Mitchell"
use cardio_long, clear

collapse (mean) meanbp=bp meanpl=pl (max) maxbp=bp maxpl=pl (min) minbp=bp minpl=pl (p50) medbp=bp medpl=pl, by(id)
```

Notice that our data are rounded to the nearest 1, unlike our egen commands, we can format our data to reflect that decimal point to two places instead of rounding up by default

```{stata collapse4}
cd "/Users/Sam/Desktop/Econ 645/Data/Mitchell"
use cardio_long, clear
format bp* pl* %5.2f
collapse (mean) meanbp=bp meanpl=pl (max) maxbp=bp maxpl=pl (min) minbp=bp minpl=pl (p50) medbp=bp medpl=pl, by(id)
```
## Exercise

Pull BLS monthly inflation data, reshape it into long, and merge with CPS
	
