# Exercises

## General Social Survey

### Explanatory and Outcomes

Steps 

  1. Use the file gss2006_chapter6.dta
  2. Our variables of focus will be *sex* and *premars*
  3. Let's answer the question: Do men and women have different views on premarital sex?
  4. Which variable is the explanatory/independent variable?
  5. Which variable is the outcome/dependent variable?
  6. Run a *tabulate* command. We want to include conditional percentage \(P(Opinion|Men) \) and \(P(Opinion | Women) \)
  7. Calculate a \( \chi^2 \) statistics.
  8. Do you find a statistically significant difference?
  9. Calculate a Cramer's V.
  10. What do you find about the relationship?
  11. Interpret the conditional percentage.
  
### Categorical and Quantitative Variables

Steps

  1. Use the file gss2006_chapter6.dta
  2. We are interested in the differences in average weekly working hours *hrs1* by political views *polviews*.
  3. Use the *table* command to find the mean, standard deviation, and frequency by political views.
  4. Do you find any differences? How do the extreme ends compare?
  5. Create a bar chart using *graph bar (mean) hrs1*. Add labels to the bars and use the options to format.

## Ordinal Variables

Steps

  1. Use the file gss2006_chapter6.dta from AGIS
  2. We are intered in the variables *polviews* and *premars*
  3. Do political views explain premartial sex opinions?
  4. Use the *tabulate* command to do a two-way tabulation or cross-tabulation 
  5. Add the appropriate option to find conditional percentages for \(P(Opinion | PolitcalView)\)
  6. Add the test statistic options for \( \chi^2 \), Cramer's \(V\), and \(\tau_b\).
  7. What do you conclude?
  8. What is the strength of the relationship?
  9. Interpret the conditional percentages.

## Current Population Survey

Steps

  1. Let's use the NBER CPS Merged Outgoing Rotation Group (MORG) data extraction
  2. The data can be directly downloaded from: https://data.nber.org/morg/annual/morg24.dta
  3. Please review the data dictionary: https://data.nber.org/morg/docs/cpsx.pdf

### Nominal and Quantitative Variables 

Steps

  1. What is the difference in earnings between union members and non-union members?
  2. Our variables of interest are *unionmme* and *earnwke*. 
  3. Use the *table* command to compare means, standard deviations, and frequencies of weekly earnings between union members and non-union members
  4. Use the *bar graph (mean)* to display differences in means between union members and non-union members.

## Nominal Variables

Steps

  1. Use the NBER CPS MORG data extraction
  2. Is there a relationship between *sex* and laborforce status *lfsr94*?
  3. Use the *tabulate* command to calculate conditional percentages.
  4. Use the options for calculating the \( \chi^2 \) and Cramer's \(V\).
  5. Interpret your results.
  6. Who is more likely to report being employed?
